version: '3'

services:
  # MariaDB 데이터베이스 서비스
  db:
    image: mariadb:latest
    container_name: vapesite-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vapesite
      MYSQL_USER: vapeuser
      MYSQL_PASSWORD: vapepassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/logs:/var/log/mysql
    networks:
      - vapesite-network

  # Next.js 애플리케이션 서비스
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vapesite-nextjs
    restart: always
    # 외부에 직접 노출하지 않고 Nginx를 통해 접근
    expose:
      - "3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://vapeuser:vapepassword@db:3306/vapesite
    # 프로덕션 환경에서는 볼륨 마운트를 제거하여 빌드된 파일이 유지되도록 함
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    networks:
      - vapesite-network

  # Nginx 웹 서버 서비스
  nginx:
    image: nginx:latest
    container_name: vapesite-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # 로그 볼륨 (로컬 디렉토리에 저장)
      - ./nginx/log:/var/log/nginx
    depends_on:
      - nextjs
    networks:
      - vapesite-network
    # 호스트 파일에 test.com을 추가해야 합니다
    extra_hosts:
      - "test.com:127.0.0.1"
      - "www.test.com:127.0.0.1"

networks:
  vapesite-network:
    driver: bridge

volumes:
  mariadb_data:
